CREATE TABLE regional (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_integrador INTEGER NOT NULL,
	nome VARCHAR(200) NOT NULL,
	ativo BOOLEAN NOT NULL DEFAULT TRUE,
	criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_regional_nome ON regional (nome);
CREATE INDEX ix_regional_ativo ON regional (ativo);
CREATE INDEX ix_regional_id_integrador ON regional (id_integrador);
