CREATE TABLE album_capa (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	album_id BIGINT NOT NULL,
	bucket VARCHAR(200) NOT NULL,
	objeto VARCHAR(500) NOT NULL,
	content_type VARCHAR(100) NOT NULL,
	tamanho BIGINT NOT NULL,
	etag VARCHAR(200),
	nome_original VARCHAR(500),
	criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_album_capa_album FOREIGN KEY (album_id) REFERENCES album (id),
	CONSTRAINT ux_album_capa_album_id UNIQUE (album_id)
);

CREATE INDEX ix_album_capa_album_id ON album_capa (album_id);
